### ISSUE TITLE
If MissionControl::Notification has even one failed send history, we mark it as warning.

### ISSUE THREAD

**Issue by adityathebe** [flanksource/is-healthy#165]
We clear up send history after 30 days, but until then the notification is marked as `warning`.

I think we should instead add `status.lastFailed` timestamp to the CRD and mark as warning if `lastFailed in the last 24hrs (...?)`

```yaml
apiVersion: mission-control.flanksource.com/v1
kind: Notification
metadata:
  uid: a37a3b53-951d-40f3-a65a-b540950ceb0f
  name: notify-recommender-playbook
  labels:
    app.kubernetes.io/managed-by: Helm
  namespace: mc
  finalizers:
    - notification.mission-control.flanksource.com
  annotations:
    meta.helm.sh/release-name: playbooks-ai
    meta.helm.sh/release-namespace: mc
  creationTimestamp: 2025-03-11T07:12:44Z
spec:
  to:
    playbook: mc/recommend-playbook
  events:
    - config.unhealthy
    - config.warning
  filter: tags.cluster == 'homelab'
  waitFor: 20s
  fallback:
    connection: connection://mc/flanksource-slack
  repeatInterval: 1d
status:
  sent: 50
  failed: 1
  lastSent: 2025-03-01T12:25:20Z
```
