### ISSUE TITLE
Add support for crossplane objects

### ISSUE THREAD

**Issue by moshloop** [flanksource/is-healthy#24]
```yaml
  conditions:
    - type: Ready
      reason: Available
      status: "True"
    - type: Synced
      reason: ReconcileSuccess
      status: "True"
    - type: LastAsyncOperation
      reason: ApplyFailure
      status: "False"
      message: "apply failed: an existing
        `high_availability.0.standby_availability_zone` can only be changed when
        exchanged with the zone specified in `zone`: "
    - type: AsyncOperation
      reason: Finished
      status: "True"
```
