### ISSUE TITLE
Add event severity

### ISSUE THREAD

**Issue by moshloop** [flanksource/is-healthy#34]
`is-healthy/events`.GetEventSeverity

Process exact matches first, and then wildcards. 

```yaml
*Failed*: medium
*IsDown: medium
*NetworkInterface: info
*Succeeded: info
*NotReady: low
AccessPolicy:  low
Add*: low
Associate*: low
Attach*: low
AttachVolume:  info
Authorize*: medium
BackOff: high
Change*: low
ConntrackFull:   med
Create*: low
Delete*: low
Deleted: info
Deleting*: low
Detach*:  low
Drain:  low
EnableMFADevice:  low
Error: medium
Evicted:  medium
EvictionThresholdMet:  low
ExceededGracePeriod:  low
ExternalExpanding:  low
ExternalProvisioning:  low
Failed*: medium
FailedCreatePodSandBox:  low
FailedDelete: low
FailedKillPod:  low
FailedMount: low
FailedPreStopHook:  low
FailedScheduling: low
FailedToUpdateEndpoint: low
FailedToUpdateEndpointSlices:  low
FileSystemResizeRequired:  low
FileSystemResizeSuccessful:  low
FreezeScheduled:  low
InvalidDiskCapacity:  med
Killing: info
KubeletIsDown: high  
MissingJob:  low
ModifyLoadBalancerAttributes:  low
ModifyNetworkInterfaceAttribute:  low
NetworkNotReady:  high
NewArtifact:  low
NodeAllocatableEnforced:  low
NodeHasDiskPressure:  high
NodeHasInsufficientMemory:  high
NodeNotReady: high
NodeNotSchedulable:  high
NodeUnderDiskPressure: low
NodeUnderMemoryPressure: medium
NodeUnreachable: high
NoPods:  low
NoSourceArtifact:   low
NotTriggerScaleUp:  low
NoVMEventScheduled:  low
OOMKilled: high
OrderCreated:  low
OrderPending:  low
PodCrashLooping:  high
PreemptScheduled:  low
Presented:  info
ProcessingError: high  
Provisioning: low
Put*: low
RebootScheduled:  low
RecreatingFailedPod: low
RedeployScheduled:  low
RegisteredNode:  low
RegisterInstancesWithLoadBalancer:  low
RELOAD:  low
RemovingNode:  low
Requested:  low
Resizing:  low
ResourceCreated:  low
ResourceUpdated:  low
Revoke*: med
Run*:   low
ScaleDown:  low
ScaledUpGroup:  low
ScalingPaused: low
ScalingReplicaSet: low
ScalingResumed: low
SourceUnavailable:  low
Started: info
Starting:  info
Succeeded:  info
Success:  info
SuccessfulAttachVolume:  info
SuccessfulCreate: info
SuccessfulDelete: info
Sync:  info
Tag*:  low
TaintManagerEviction: low  
TerminateScheduled:  low
TriggeredScaleUp:  low
UnexpectedJob:  medium
Unhealthy: medium
Update*: low
Updated: info
UpdatedLoadBalancer:  low
Upgrade:  low
VMEventScheduled:  low
Cannot*: medium
DeletedExternalResource: low
CreatedExternalResource: low
UpdatedExternalResource: low
ReconciliationPaused: low
```

And then plug into config-db, to add severities to changes
