### ISSUE TITLE
Fix health status

### ISSUE THREAD

**Issue by moshloop** [flanksource/is-healthy#39]
- [x] Any flux -  ReconciliationSucceeded  -> Healthy
- [ ] Node Healthy -> Healthy
- [x] StatefulSet replicas=0 && status.replicas=0 -> Scaled to Zero
- [x] PodUnschedulable 
```yaml
  conditions:
    - type: PodScheduled
      reason: Unschedulable
      status: "False"
      message: "0/5 nodes are available: 1 Insufficient cpu, 1 Insufficient memory, 4
        node(s) didn't match Pod's node affinity/selector. preemption: 0/5 nodes
        are available: 1 No preemption victims found for incoming pod, 4
        Preemption is not helpful for scheduling."
```
