### ISSUE TITLE
Helm upgrade failure

### ISSUE THREAD

**Issue by moshloop** [flanksource/is-healthy#41]
```yaml
  conditions:
    - type: Reconciling
      reason: Progressing
      status: "True"
      message: Running 'upgrade' action with timeout of 5m0s
    - type: Ready
      reason: UpgradeFailed
      status: "False"
      message: "Helm upgrade failed for release
        mission-control-agent/prod-kubernetes-bundle with chart
        mission-control-kubernetes@0.1.29: YAML parse error on
        mission-control-kubernetes/templates/topology.yaml: error converting
        YAML to JSON: yaml: line 171: did not find expected '-' indicator"
    - type: Released
      reason: UpgradeFailed
      status: "False"
      message: "Helm upgrade failed for release
        mission-control-agent/prod-kubernetes-bundle with chart
        mission-control-kubernetes@0.1.29: YAML parse error on
        mission-control-kubernetes/templates/topology.yaml: error converting
        YAML to JSON: yaml: line 171: did not find expected '-' indicator"
  storageNamespace: mission-control-agent
  lastAttemptedRevision: 0.1.29
  lastAttemptedGeneration: 1
  lastAttemptedConfigDigest: sha256:e6dfc2b4a98058b60adc4fb33ed42d5e80f88471a4f9eb3e272709bf69417a32
  lastAttemptedReleaseAction: upgrade
```

Progressing should have a lower priority than UpgradeFail;ed
