### ISSUE TITLE
Evicted pods

### ISSUE THREAD

**Issue by moshloop** [flanksource/is-healthy#44]
```yaml
status:
  phase: Failed
  podIP: 10.101.16.203
  hostIP: 10.101.0.7
  podIPs:
    - ip: 10.101.16.203
  reason: Evicted
  message: "The node was low on resource: memory. Threshold quantity: 750Mi,
    available: 179968Ki. "
  qosClass: Burstable
  startTime: 2024-05-22T09:52:34Z
  conditions:
```

Mark as warning, and ready: true
