### ISSUE TITLE
1 shot pods

### ISSUE THREAD

**Issue by moshloop** [flanksource/is-healthy#65]
```yaml
  conditions:
    - type: Initialized
      reason: PodCompleted
      status: "True"
    - type: Ready
      reason: PodCompleted
      status: "False"
    - type: ContainersReady
      reason: PodCompleted
      status: "False"
    - type: PodScheduled
      status: "True"
  containerStatuses:
    - name: clients-fargate-alert
      image: docker.infoslipscloud.com/iiab-cronjobs:latest
      ready: false
      state:
        terminated:
          reason: Completed
          exitCode: 0
          startedAt: 2024-07-04T00:05:00Z
          finishedAt: 2024-07-04T00:05:02Z
          containerID: containerd://5f7ccc46f8cd10aa760db32348c6619485ccfe9715c58b43bbee3705ab584752
      imageID: docker.infoslipscloud.com/iiab-cronjobs@sha256:1c0237f08b4d7343c8a6fc8e455e5ecd949a3768596b4af9141f65f9fc3bcc08
      started: false
      lastState: {}
      containerID: containerd://5f7ccc46f8cd10aa760db32348c6619485ccfe9715c58b43bbee3705ab584752
      restartCount: 0
```
