### ISSUE TITLE
Pod that completed but are still running

### ISSUE THREAD

**Issue by moshloop** [flanksource/is-healthy#72]
Scraped at: 2024-07-18T19:31:46.307804+00:00"

```
status:
  phase: Running
  podIP: 168.1.91.19
  hostIP: 168.1.75.190
  podIPs:
    - ip: 168.1.91.19
  qosClass: BestEffort
  startTime: 2024-04-30T06:48:47Z
  conditions:
    - type: Initialized
      status: "True"
    - type: Ready
      status: "True"
    - type: ContainersReady
      status: "True"
    - type: PodScheduled
      status: "True"
  containerStatuses:
    - name: gitlab-runner
      image: registry.gitlab.com/gitlab-org/gitlab-runner:alpine-v16.9.1
      ready: true
      state:
        running:
          startedAt: 2024-07-18T12:03:06Z
      imageID: registry.gitlab.com/gitlab-org/gitlab-runner@sha256:930288bf8b56a1dfcdee733a98b6b30e35b9b4c48bd07250d5eb4db822e3ec13
      started: true
      lastState:
        terminated:
          reason: Completed
          exitCode: 0
          startedAt: 2024-07-18T11:56:37Z
          finishedAt: 2024-07-18T12:03:06Z
          containerID: containerd://8d09ffbf6619b1de506c812a0ad0a8e4f133d8c2b6ec07758bc768261bf34931
      containerID: containerd://418ea5c9ff6a4877399782c769d673aa83baeaa95d28d5b1cf9d4ff4354dd4d1
      restartCount: 9

```

**Comment by moshloop** [comment]
And this pod that has started,  but turned not ready - i.e. Status should be Not Ready with warning health (Unknown if the start time is `< readinessProbe.initialDelaySeconds + (   (periodSeconds + timeoutSeconds) * failureThreshold`


```
status:
  phase: Running
  podIP: 10.0.179.6
  hostIP: 10.0.179.6
  podIPs:
    - ip: 10.0.179.6
  hostIPs:
    - ip: 10.0.179.6
  qosClass: BestEffort
  startTime: 2024-07-17T06:58:33Z
  conditions:
    - type: PodReadyToStartContainers
      status: "True"
    - type: Initialized
      status: "True"
    - type: Ready
      status: "False"
    - type: ContainersReady
      status: "True"
    - type: PodScheduled
      status: "True"
  containerStatuses:
    - name: eks-pod-identity-agent
      image: 602401143452.dkr.ecr.eu-west-1.amazonaws.com/eks/eks-pod-identity-agent:0.1.10
      ready: true
      state:
        running:
          startedAt: 2024-07-17T06:58:43Z
      imageID: 602401143452.dkr.ecr.eu-west-1.amazonaws.com/eks/eks-pod-identity-agent@sha256:9cf48154b1603963d449f80ed8bc150918509ac025e92cdd67748a9f3f8ad367
      started: true
      lastState: {}
      containerID: containerd://8e48835f5f3765827aed1470ef5a95312345c52a1a5c3db24ff800c8e10a6424
      restartCount: 0
  initContainerStatuses:
    - name: eks-pod-identity-agent-init
      image: 602401143452.dkr.ecr.eu-west-1.amazonaws.com/eks/eks-pod-identity-agent:0.1.10
      ready: true
      state:
        terminated:
          reason: Completed
          exitCode: 0
          startedAt: 2024-07-17T06:58:37Z
          finishedAt: 2024-07-17T06:58:37Z
          containerID: containerd://16032f42f71448ef31794b6805cb69f25cc4e59fd83622d3fa9b3acd00a3867c
      imageID: 602401143452.dkr.ecr.eu-west-1.amazonaws.com/eks/eks-pod-identity-agent@sha256:9cf48154b1603963d449f80ed8bc150918509ac025e92cdd67748a9f3f8ad367
      started: false
      lastState: {}
      containerID: containerd://16032f42f71448ef31794b6805cb69f25cc4e59fd83622d3fa9b3acd00a3867c
      restartCount: 0
```
